# Generated by Django 4.1.2 on 2022-10-23 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microblogs', '0003_rename_test_post_text_alter_post_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_at']},
        ),
    ]
