# Generated by Django 3.2.16 on 2023-06-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microblogs', '0006_auto_20230603_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
