# Generated by Django 3.2.16 on 2023-06-04 14:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microblogs', '0007_alter_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follows',
            field=models.ManyToManyField(related_name='_microblogs_user_follows_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
