# Generated by Django 3.2.16 on 2023-06-05 15:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microblogs', '0008_user_follows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='follows',
            field=models.ManyToManyField(related_name='user_follows', to=settings.AUTH_USER_MODEL),
        ),
    ]
